# Generated by Django 4.0.4 on 2022-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=20)),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
