# Generated by Django 4.0.4 on 2022-05-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foo',
            old_name='first_name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='foo',
            old_name='last_name',
            new_name='country_size',
        ),
        migrations.RenameField(
            model_name='foo',
            old_name='company_name',
            new_name='presidents_name',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='salary',
        ),
        migrations.AddField(
            model_name='foo',
            name='ethnicity',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
